version: "2"

services:

  rabbitmq:
    build: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672

  # zookeeper:
  #   image: docker.io/bitnami/zookeeper:3.7
  #   # restart: unless-stopped
  #   ports:
  #     - "2181:2181"
  #   # volumes:
  #   #   - "./zookeeper_data:/bitnami"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  # kafka:
  #   image: docker.io/bitnami/kafka:3
  #   # restart: unless-stopped
  #   ports:
  #     - "9092:9092"
  #   # volumes:
  #   #   - "./kafka_data:/bitnami"
  #   #   - "./kafka_brokers:/brokers"
  #   environment:
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper
  #
  # apicurio:
  #   image: apicurio/apicurio-registry-mem
  #   ports:
  #     - 8081:8081


  # activemq:
  #   image: artemis-adoptopenjdk-11
  #   ports:
  #     - 5672:5672
